name: 'GitHub Actions'
'on':
  - push
concurrency: 'ci-${{ github.ref }}'
env:
  APP_IMAGE: keboola/google-client-bundle
  DOCKERHUB_USER: '${{ secrets.DOCKERHUB_USER }}'
  DOCKERHUB_TOKEN: '${{ secrets.DOCKERHUB_TOKEN }}'

  CLIENT_ID: '${{ secrets.CLIENT_ID }}'
  CLIENT_SECRET: '${{ secrets.CLIENT_SECRET }}'
  REFRESH_TOKEN: '${{ secrets.REFRESH_TOKEN }}'
  SERVICE_ACCOUNT_JSON: '${{ secrets.SERVICE_ACCOUNT_JSON }}'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Check out the repo'
        uses: actions/checkout@v2
      -
        name: 'Docker login'
        if: env.DOCKERHUB_TOKEN
        run: 'docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"'
      -
        name: 'Build image'
        run: 'docker build -t $APP_IMAGE .'
      -
        name: 'Run tests'
        run: |
          docker run \
          -e CLIENT_ID \
          -e CLIENT_SECRET \
          -e REFRESH_TOKEN \
          -e SERVICE_ACCOUNT_JSON \
          ${{env.APP_IMAGE}} composer ci
